### ISSUE TITLE
Support for keyword spotting while real time inference

### ISSUE THREAD

**Issue by axchanda** [daanzu/deepspeech-websocket-server#4]
Hi @daanzu Is there a possibility on how we can add keyword spotting while inferencing in real time. Like spotting custom words or giving priority to certain words on the fly just like phrases in Google Speech API. Also, would like to ask whether has Deepspeech come up with real time in the original version? Quick answers appreciated.

**Comment by daanzu** [comment]
I don't think [DeepSpeech](https://github.com/mozilla/DeepSpeech) supports keyword spotting, custom words or giving priority to certain words currently. This project is mostly just a wrapper around it for now.
